pip install numpy

In [ ]:
nums=[1,2,3,4,5,6,7,8,9]
#print(type(nums))
sq=[]
for n in nums:
  sq.append(n**2)

print(sq)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
nums=[1,2,3,4,5,6,7,8,9]
sq=[x**2 for x in nums]
print(sq)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [2]:
import numpy

In [ ]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
sq=arr**2
print(sq)

[ 1  4  9 16 25 36 49 64 81]


**Creating numpy array from 1D list**

In [ ]:
lst=[9,26,13,1,45,30,12,10,89,31]
arr=numpy.array(lst)
print(lst)
print(arr)
print(type(arr))

[9, 26, 13, 1, 45, 30, 12, 10, 89, 31]
[ 9 26 13  1 45 30 12 10 89 31]
<class 'numpy.ndarray'>


**Creating numpy array from 2D lists**

In [ ]:
lst=[
    [5,2,1,8],
    [3,9,2,1],
    [4,1,6,7]
]
print(lst)

[[5, 2, 1, 8], [3, 9, 2, 1], [4, 1, 6, 7]]


In [ ]:
arr=numpy.array(lst)
print(arr)

[[5 2 1 8]
 [3 9 2 1]
 [4 1 6 7]]


**Creating numpy array with 0's and 1's**

In [ ]:
z=numpy.zeros((4,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
o=numpy.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr=numpy.full((3,5),9)
print(arr)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


**Creating identity matrix**

In [ ]:
arr=numpy.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**create numpy array using arange()**

In [3]:
arr=numpy.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
arr=numpy.arange(45,70,2)
print(arr)

[45 47 49 51 53 55 57 59 61 63 65 67 69]


In [5]:
arr=numpy.arange(50,25,-3)
print(arr)

[50 47 44 41 38 35 32 29 26]


**creating numpy array using linear spacing**

In [6]:
arr=numpy.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
arr=numpy.linspace(1,13,9)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]


**Multiple types**

In [8]:
lst=['praffull',9,68.14,True]
for value in lst:
  print(type(value))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [9]:
arr=numpy.array(lst)
print(arr)

['praffull' '9' '68.14' 'True']
