In [1]:
import numpy

In [2]:
arr=numpy.random.random(10)
print(arr)

[0.63074621 0.63578268 0.23483888 0.80361563 0.23269357 0.32886643
 0.81854529 0.73028571 0.34061083 0.7219087 ]


In [5]:
arr=numpy.random.random((3,5))
print(arr)

[[0.92834814 0.85199809 0.65277539 0.75401481 0.36612197]
 [0.90369054 0.04183787 0.00556902 0.72380808 0.05046133]
 [0.97500625 0.54698474 0.74745431 0.28100516 0.23985095]]


In [11]:
arr=numpy.random.randint(10)
print(arr)

8


In [12]:
arr=numpy.random.randint(1,50,10)
print(arr)

[49 49 24  2 11 32 30 28 27 24]


In [14]:
arr=numpy.random.randint(1,100,(5,7))
print(arr)

[[26  3 59 60 10 96 83]
 [55 21 87 21 23 79 49]
 [76 79 29 31 42 44 56]
 [72 73 56 55 90 65 41]
 [ 7 56 75 67 12 80 18]]
