In [3]:
import numpy

**Basic maths**

In [5]:
a1=numpy.array([1,2,3,4])
a2=numpy.array([7,5,8,9])
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)

[ 8  7 11 13]
[6 3 5 5]
[ 7 10 24 36]
[7.         2.5        2.66666667 2.25      ]


**Scalar operations**

In [ ]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])
print(arr+5)
print(arr*2)
print(arr**2)

[ 6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14 16 18]
[ 1  4  9 16 25 36 49 64 81]


**Aggregate operations**

In [ ]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.var())
print(numpy.corrcoef(arr))
print(arr.max())
print(arr.min())

45
5.0
2.581988897471611
6.666666666666667
1.0
9
1


**Elementwise operations**

In [ ]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])
print(numpy.sqrt(arr))
print(numpy.sin(arr))
print(numpy.cos(arr))
print(numpy.tan(arr))
print(numpy.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


**rounding and absolute**

In [7]:
arr=numpy.array([1.4,3.6,-4,-5.7])
print(numpy.round(arr))
print(numpy.abs(arr))

[ 1.  4. -4. -6.]
[1.4 3.6 4.  5.7]


**Comparisons**

In [10]:
a1=numpy.array([1,2,3])
a2=numpy.array([4,2,5])
print(a1==a2)
res=(a1==a2)
print(res.all())

[False  True False]
False


In [11]:
print(a1>a2)

[False False False]


In [14]:
a1=numpy.array([[12,23],[45,34],[65,49]])
a2=numpy.array([[11,59],[45,73],[71,49]])
comp=(a1==a2)
print(comp)
if comp.all():
  print("the numpy array have same values")
else:
  print("values in numpy arrays are different")

[[False False]
 [ True False]
 [False  True]]
values in numpy arrays are different


**Cumulative result**

In [15]:
arr=numpy.array([1,2,3,4,5])
print(numpy.cumsum(arr))

[ 1  3  6 10 15]
