In [1]:
import numpy

In [2]:
a1=numpy.array([1,2,3,4,5])
a2=numpy.array([10,20,30,40,50,60,70])
res=numpy.concatenate((a1,a2))
print(res)

[ 1  2  3  4  5 10 20 30 40 50 60 70]


In [7]:
a1=numpy.array([[1,2,3],[4,5,6]])
a2=numpy.array([[12,23,34],[56,67,78],[89,90,76]])
res=numpy.concatenate((a1,a2))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [12 23 34]
 [56 67 78]
 [89 90 76]]


In [11]:
a1=numpy.array([[1,2,3],[4,5,6]])
print(a1.shape)
a2=numpy.array([[12,23],[45,56]])
print(a2.shape)
res=numpy.concatenate((a1,a2),axis=1)
print(res)

(2, 3)
(2, 2)
[[ 1  2  3 12 23]
 [ 4  5  6 45 56]]
