In [1]:
import numpy

In [2]:
arr=numpy.array([12,23,34,45,56,67,78,89,90])
print(arr)

[12 23 34 45 56 67 78 89 90]


In [3]:
print(arr[0])

12


In [4]:
print(arr[2:5])

[34 45 56]


In [5]:
print(arr[-1])

90


In [6]:
print(arr[::-1])

[90 89 78 67 56 45 34 23 12]


In [7]:
print(arr[3:])
print(arr[:4])

[45 56 67 78 89 90]
[12 23 34 45]


In [8]:
lst=[
    [12,23,34,45,56],
    [54,43,32,21,76],
    [21,47,33,69,26]
]
arr=numpy.array(lst)
print(arr)

[[12 23 34 45 56]
 [54 43 32 21 76]
 [21 47 33 69 26]]


In [9]:
print(arr[:,:])

[[12 23 34 45 56]
 [54 43 32 21 76]
 [21 47 33 69 26]]


In [10]:
print(arr[1,3])

21


In [11]:
print(arr[1:,:])

[[54 43 32 21 76]
 [21 47 33 69 26]]


In [12]:
print(arr[1:,1:3])

[[43 32]
 [47 33]]
