In [1]:
import numpy

**Filter**

In [2]:
arr=numpy.random.randint(1,75,10)
print(arr)

[19 73 34 53 25 51 57  5  3  4]


In [3]:
filtered=arr[arr>50]
print(filtered)

[73 53 51 57]


In [6]:
print(arr[arr%2==1])
print(arr[arr%2==0])

[19 73 53 25 51 57  5  3]
[34  4]


**Sort**

In [7]:
arr=numpy.random.randint(25,100,10)
print(arr)

[40 92 45 68 29 91 53 81 45 55]


In [8]:
print(numpy.sort(arr))

[29 40 45 45 53 55 68 81 91 92]


In [9]:
print(numpy.sort(arr)[::-1])

[92 91 81 68 55 53 45 45 40 29]


**Unique**

In [10]:
arr=numpy.array([9,26,13,45,1,9,25,29,1,13,9,26,45])
print(arr)

[ 9 26 13 45  1  9 25 29  1 13  9 26 45]


In [11]:
un=numpy.unique(arr)
print(un)

[ 1  9 13 25 26 29 45]


**Split**

In [14]:
arr=numpy.array([9,26,13,45,1,9,25,29,1,13,9,26,45,13,1])
print(arr.shape)
print(numpy.split(arr,5))

(15,)
[array([ 9, 26, 13]), array([45,  1,  9]), array([25, 29,  1]), array([13,  9, 26]), array([45, 13,  1])]


In [16]:
arr=numpy.array([9,26,13,45,1,9,25,29,1,13,9,26])
print(arr.shape)
print(numpy.split(arr,5))

(12,)


ValueError: array split does not result in an equal division

In [17]:
arr=numpy.array([9,26,13,45,1,9,25,29,1,13,9,26])
print(arr.shape)
print(numpy.array_split(arr,5))

(12,)
[array([ 9, 26, 13]), array([45,  1,  9]), array([25, 29]), array([ 1, 13]), array([ 9, 26])]
